export const QK = {
  ACCOUNTS: 'accounts',
  ANNUAL_2025_ANALYSIS: 'annual-2025-analysis',
  ANNUAL_2026_ANALYSIS: 'annual-2026-analysis',
  ANNUAL_PROJECTION_OVERVIEW_2026: 'annual-projection-overview-2026',
  BUDGET_ANALYTICS: 'budget-analytics',
  BUDGET_METRICS_BUCKET_MAP: 'budget-metrics-bucket-map',
  BUDGET_METRICS_CATEGORIES: 'budget-metrics-categories',
  BUDGET_METRICS_PERIOD_DATASET: 'budget-metrics-period-dataset',
  BUDGET_METRICS_YEAR_DATASET: 'budget-metrics-year-dataset',
  BUDGET_PAYLOAD: 'budget-payload',
  BUDGET_PERIODS: 'budget-periods',
  BUDGET_REVENUE_ANALYTICS: 'budget-revenue-analytics',
  BUDGETS: 'budgets',
  CATEGORIES: 'categories',
  CATEGORY_ANNUAL_COST_PROJECTION_2026: 'category-annual-cost-projection-2026',
  CATEGORY_ROLLING_12M_STATS: 'category-rolling-12m-stats',
  COMPARED_BUCKET_SUMMARY: 'compared-bucket-summary',
  COMPARED_CATEGORY_SUMMARY: 'compared-category-summary',
  COMPARED_YTD_FLOWS: 'compared-ytd-flows',
  COMPARED_YTD_FLOWS_KPI_CARDS: 'compared-ytd-flows-kpi-cards',
  DAILY_CASHFLOW_FORECAST: 'daily-cashflow-forecast',
  HOME: 'home',
  HOME_DAILY_BUDGET: 'home-daily-budget',
  MONTHLY_FLOWS_ANALYSIS_CARD: 'monthly-flows-analysis-card',
  MONTHLY_FLOWS_BY_SCOPE: 'monthly-flows-by-scope',
  PERIOD: 'period',
  PLANNED_OPERATIONS: 'planned-operations',
  SAVINGS: 'savings',
  SAVINGS_ACCOUNTS_DISPLAY: 'savings-accounts-display',
  SAVINGS_ANALYTICS: 'savings-analytics',
  SAVINGS_ANNUAL_PERFORMANCE: 'savings-annual-performance',
  SAVINGS_CURRENT_SUMMARY: 'savings-current-summary',
  SAVINGS_EVOLUTION_5Y: 'savings-evolution-5y',
  STATS: 'stats',
  STATS_REFERENCE: 'stats-reference',
  TRANSACTIONS: 'transactions',
  TRIP_COCKPIT: 'trip-cockpit',
  TRIP_EXPENSES: 'trip-expenses',
  TRIP_MANUAL_EXPENSES: 'trip-manual-expenses',
  TRIP_MATCH_CANDIDATES: 'trip-match-candidates',
  TRIPS_FOR_MONTH: 'trips-for-month',
  VOYAGES: 'voyages',
  VOYAGES_ALL: 'voyages-all',
  VOYAGES_TRANSACTIONS: 'voyages-transactions',
} as const

/** Stable stale times (ms) — single source of truth */
export const STALE = {
  /** Live operational data: budgets, transactions, accounts */
  LIVE: 60_000,
  /** Analytical data refreshed at most every 5 min */
  ANALYTICS: 5 * 60_000,
  /** Historical/reference data — rarely changes */
  HISTORICAL: 15 * 60_000,
} as const
